### PR TITLE
Adding basic ESLint config

### PR DESCRIPTION
**Pull request by pdehaan**
This only adds ESLint, not CSS/style linting.

Ref: #27

### CODE REVIEW

**Comment by ericawright** [comment]
Looks good. But prettier is already in, we don't need both, right? I haven't figured out how to customize prettier yet, so I prefer this ;)

**Comment by pdehaan** [comment]
Well... I think **prettier** is more for code _formatting_, whereas **eslint** is better suited for code _validation_ and enforcing rules. Definitely some areas of overlap (indentation, quotes, etc) though.

We _could_ use **prettier** as a plugin for **eslint** using something like [**eslint-plugin-prettier**](https://github.com/prettier/eslint-plugin-prettier), but I find that flow a bit awkward and difficult to maintain.

**Comment by dannycoates** [comment]
Thanks @pdehaan!

@abhinadduri @dnarcese let's get this merged after #71 then create an issue to fix the lint errors

**Comment by pdehaan** [comment]
@dannycoates Rebased. 👀

**Pull request merged**
